### ISSUE TITLE
Compile error while manually importing on Xcode 11.5

### ISSUE THREAD

**Issue by migfabio** [jonreid/ViewControllerPresentationSpy#1]
Hi, I've manually added your framework into my test target (see my configuration) and I got this error:

> Building for iOS Simulator, but the linked and embedded framework 'ViewControllerPresentationSpy.framework' was built for iOS.

<img width="807" alt="Screenshot 2020-06-09 at 18 56 18" src="https://user-images.githubusercontent.com/4320402/84182834-f4ef1100-aa82-11ea-869c-4b556f9d1580.png">

**Comment by jonreid** [comment]
Reproduced.

**Comment by jonreid** [comment]
Fixed. I've put up a fresh pre-built release. Thank you!
