### ISSUE TITLE
Document or add GitHub action to build framework binaries

### ISSUE THREAD

**Issue by kikeenrique** [jonreid/ViewControllerPresentationSpy#10]
Hi,

Thanks for maintaining this project. I think it has many useful concepts/helpers.

I'm using the code examples on the book **Unit testing by example**, and I'm getting a compiler error using Xcode 13 beta (I guess on Xcode 12.5 it would be reproducible, as latest binaries provided are for Xcode 12.3).

This is the error log:
```
Module compiled with Swift 5.2 cannot be imported by the Swift 5.5 compiler: 
~/Developer/ios/unit-testing-by-example-code/Alert/AlertTests/ViewControllerPresentationSpy.framework/Modules/ViewControllerPresentationSpy.swiftmodule/x86_64.swiftmodule
```

What I miss are the instructions that I guess you have used to build the frameworks for the Prebuild binaries.
Have you also thought of adding a GitHub action for that, in order for the instructions to be always updated?

Regards

**Comment by jonreid** [comment]
I just added instructions to the bottom of the README for how to build on your own.
