### ISSUE TITLE
Module compiled with Swift 5.4 cannot be imported by the Swift 5.5 compiler

### ISSUE THREAD

**Issue by Sangsom** [jonreid/ViewControllerPresentationSpy#12]
Hey there recently I've got updated Xcode and now I'm receiving following errors after importing `ViewControllerPresentationSpy`.

```
Module compiled with Swift 5.4 cannot be imported by the Swift 5.5 compiler: /Users/sangsom/Developer/Pragmatic coding/My code/Navigation/NavigationTests/ViewControllerPresentationSpy-5.1.0/ViewControllerPresentationSpy.framework/Modules/ViewControllerPresentationSpy.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

Module compiled with Swift 5.4 cannot be imported by the Swift 5.5 compiler: /Users/sangsom/Developer/Pragmatic coding/My code/Navigation/NavigationTests/ViewControllerPresentationSpy-5.1.0/ViewControllerPresentationSpy.framework/Modules/ViewControllerPresentationSpy.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```

**Comment by dsanjrani** [comment]
Hey,
you can download or clone the repository and execute the script Source/MakeDistribution.sh in your Terminal. That will create a fresh version of the framework using the Xcode version on your machine (which probably builds it with Swift 5.5).

**Comment by Sangsom** [comment]
Thank you for suggestion! Appreciate!

**Comment by jonreid** [comment]
Thank you, @dsanjrani 
@Sangsom let me know if you have questions. It really depends on what mechanism you use to bring in the code. I try to keep https://github.com/jonreid/ViewControllerPresentationSpy/releases updated with compiler-specific builds.
