### ISSUE TITLE
In Xcode 14.3 I got this error "Multiple commands produce"

### ISSUE THREAD

**Issue by CarlosP10** [jonreid/ViewControllerPresentationSpy#15]
Steps to get this error
1. Import ViewControllerPresentationSpy.xcframework in TestTarget
2. Clic on Tests target ->select the Build Phases tab -> New Copy Files Phase -> Products Directory -> add select ViewControllerPresentationSpy.framework
3. Build test target and get that error
Multiple commands produce '/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/ViewControllerPresentationSpy.framework'

**Comment by icedice** [comment]
I know this is a late reply, did you figure it out?
Are you embedding the framework?  If so I don't see why the copy phase would be needed, try removing it and see if that works.

**Comment by jonreid** [comment]
@CarlosP10 Let me know if this is still an issue. I'm closing this for now.
