### ISSUE TITLE
Update framework so that it can be used in Xcode 12

### ISSUE THREAD

**Issue by andrewmarmion** [jonreid/ViewControllerPresentationSpy#3]
Currently when adding the framework to an Xcode 12 created project  it complains that the module ViewControllerPresentationSpy was compiled with Swift 5.2.4 and it cannot be imported by the Swift 5.3 compiler.

Would it be possible to have the framework updated so that it can be imported by the Swift 5.3 compiler?

**Comment by jonreid** [comment]
Sorry I didn't notice your issue until now.
Should be fixed in https://github.com/jonreid/ViewControllerPresentationSpy/releases/tag/v5.1.0
