### ISSUE TITLE
Module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler:

### ISSUE THREAD

**Issue by yangwulong1978** [jonreid/ViewControllerPresentationSpy#5]
downloaded your book code, under Navigation folder that project, build and run test got this issue.

**Comment by yangwulong1978** [comment]
chapter 13 has same issue.

**Comment by jonreid** [comment]
Should now be available in https://github.com/jonreid/ViewControllerPresentationSpy/releases/tag/v5.1.0
Thank you for supporting my writing!
