### ISSUE TITLE
Build fails after Cocoapods install

### ISSUE THREAD

**Issue by cduhn** [jonreid/ViewControllerPresentationSpy#6]
After installing via cocoapods, my build fails with the error: `ViewControllerPresentationSpy/ViewControllerPresentationSpy-Swift.h' file not found` on line 8 of UIViewController+QCOMock.m:

```
#import <ViewControllerPresentationSpy/ViewControllerPresentationSpy-Swift.h>
```

That header file doesn't seem to exist. When I run `find . |grep ViewControllerPresentationSpy-Swift` at the root of my project, I get no matches.

I'm running Cocoapods version 1.9.3 with Xcode version 12.3. I confirmed that my project's build settings aren't overriding any of the settings set by the cocoapods Config.File.

**Comment by jonreid** [comment]
Sorry for not noticing your issue until now.
Is your project ObjC only?
